//
//  FAQPage.swift
//  freebnb
//
//  Created by Irene Tang on 4/3/26.
//

import SwiftUI

struct FAQItem: Identifiable {
    let id = UUID()
    let question: String
    let answer: String
}

struct FAQPage: View {
    private let faqs: [FAQItem] = [
        FAQItem(
            question: "Is FreeBNB really free?",
            answer: "Yes, completely. There are no booking fees, service charges, or hidden costs. Hosts share their space voluntarily."
        ),
        FAQItem(
            question: "Who can see my listing?",
            answer: "Only people you've approved. Your listing is never visible to the general public or to strangers."
        ),
        FAQItem(
            question: "How is FreeBNB different from Couchsurfing or other home-sharing platforms?",
            answer: "FreeBNB is built around trust, not strangers. Unlike Couchsurfing or similar platforms where you open your home to the public, FreeBNB is invite-only: you only see listings from people already in your network of trusted contacts. There's no public marketplace, no reviews from strangers, and no algorithm matching you with random people. Your guests are people you already know or are at most a step removed from, not strangers you met online."
        ),
        FAQItem(
            question: "Does FreeBNB track my location?",
            answer: "No. FreeBNB never requests or tracks your device's location. The map you see on a listing is generated by converting the host's written address into coordinates; your own location is not used or shared. You won't see a location permission prompt because the app doesn't ask for one."
        ),
        FAQItem(
            question: "Does FreeBNB store my password?",
            answer: "No. FreeBNB uses Sign in with Apple, so your password is managed entirely by Apple. We never see it, receive it, or store it. FreeBNB only receives a unique identifier and, if you choose to share it, your name and email address. Your Apple ID credentials stay between you and Apple."
        ),
        FAQItem(
            question: "What data does FreeBNB actually store about me?",
            answer: "Only what you choose to share: your display name and email address (if you share them via Sign in with Apple). FreeBNB does not store passwords, payment information, or location data. You can delete your account at any time from the Profile page, which removes all stored data."
        )
    ]

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                ForEach(faqs) { faq in
                    VStack(alignment: .leading, spacing: 6) {
                        Text(faq.question)
                            .font(.headline)
                        Text(faq.answer)
                            .font(.subheadline)
                    }
                }
            }
            .frame(maxWidth: 600)
            .padding(30)
            .frame(maxWidth: .infinity, alignment: .center)
        }
        .background(Color.creamWhite)
        .navigationTitle("FAQ")
    }
}

#Preview {
    NavigationStack {
        FAQPage()
    }
}
