//
//  FAQPage.swift
//  freebnb
//

import SwiftUI

struct FAQItem: Identifiable {
    let id = UUID()
    let question: String
    let answer: String
}

struct FAQPage: View {
    private let faqs: [FAQItem] = [
        FAQItem(
            question: "Is FreeBNB really free?",
            answer: "Yes, completely. There are no booking fees, service charges, or hidden costs. Hosts share their space voluntarily."
        ),
        FAQItem(
            question: "Who can see my listing?",
            // swiftlint:disable:next line_length
            answer: "Only your FreeBNB friends: people whose friend request you accepted, or who accepted yours. Your listing is never public, and friends of your friends cannot see it either; they can only find you under \"People you may know\" and send a request. Removing a friend hides your listing from them again."
        ),
        FAQItem(
            question: "Who can request to stay at my place?",
            // swiftlint:disable:next line_length
            answer: "The same people who can see it: your accepted friends, and no one else. A request is only a request; nothing is confirmed until you accept it, and your exact address is shared only after you accept a stay. Until then, guests see the neighborhood."
        ),
        FAQItem(
            question: "What happens when I accept a friend request?",
            // swiftlint:disable:next line_length
            answer: "You each see the other's listings and can request to stay with each other. That is the whole grant: no payment and no obligation, and you can unfriend someone at any time from their profile, which hides your listings from them again."
        ),
        FAQItem(
            question: "How is FreeBNB different from Couchsurfing or other home-sharing platforms?",
            // swiftlint:disable:next line_length
            answer: "FreeBNB is built around trust, not strangers. Unlike Couchsurfing or similar platforms where you open your home to the public, FreeBNB is invite-only: you only see listings from your own friends. There's no public marketplace, no reviews from strangers, and no algorithm matching you with random people. Your guests are people you know and chose to connect with, not strangers you met online."
        ),
        FAQItem(
            question: "Does FreeBNB track my location?",
            // swiftlint:disable:next line_length
            answer: "No. FreeBNB never requests or tracks your device's location. The map you see on a listing is generated by converting the host's written address into coordinates; your own location is not used or shared. You won't see a location permission prompt because the app doesn't ask for one."
        ),
        FAQItem(
            question: "Does FreeBNB store my password?",
            // swiftlint:disable:next line_length
            answer: "No. FreeBNB uses Sign in with Apple, so your password is managed entirely by Apple. We never see it, receive it, or store it. FreeBNB only receives a unique identifier and, if you choose to share it, your name and email address. Your Apple ID credentials stay between you and Apple."
        ),
        FAQItem(
            question: "What data does FreeBNB actually store about me?",
            // swiftlint:disable:next line_length
            answer: "Only what you choose to share: your display name and email address (if you share them via Sign in with Apple). FreeBNB does not store passwords, payment information, or location data. You can delete your account at any time from the Profile page, which removes all stored data."
        ),
        FAQItem(
            question: "Can I browse and message hosts without creating an account?",
            // swiftlint:disable:next line_length
            answer: "No. Every host on FreeBNB is someone you know, so every guest needs to be someone identifiable too — FreeBNB uses Sign in with Apple for every account, with no anonymous browsing."
        )
    ]

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                ForEach(faqs) { faq in
                    VStack(alignment: .leading, spacing: 6) {
                        Text(faq.question)
                            .font(.headline)
                        Text(faq.answer)
                            .font(.subheadline)
                    }
                }
            }
            .frame(maxWidth: 600)
            .padding(30)
            .frame(maxWidth: .infinity, alignment: .center)
        }
        .background(Color.primaryBackground)
        .navigationTitle("FAQ")
    }
}

#Preview {
    NavigationStack {
        FAQPage()
    }
}
